version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  flathunter:
    build: ./flathunter
    volumes:
      - ./data:/app/database
      - ./config/config.yaml:/app/config/config.yaml
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"

  messagesender:
    build: ./messagesender
    volumes:
      - ./messagesender/config.yaml:/home/flathunter/config.yaml
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
